In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

In [4]:
import os
print(os.listdir("."))

['.ipynb_checkpoints', 'Price Prediction.ipynb', 'testset.csv', 'trainset.csv']


In [5]:
dataset_train = pd.read_csv("trainset.csv")

In [6]:
dataset_train

Date         Open         High          Low        Close  \
0     2013-01-02   357.385559   361.151062   355.959839   359.288177   
1     2013-01-03   360.122742   363.600128   358.031342   359.496826   
2     2013-01-04   362.313507   368.339294   361.488861   366.600616   
3     2013-01-07   365.348755   367.301056   362.929504   365.001007   
4     2013-01-08   365.393463   365.771027   359.874359   364.280701   
...          ...          ...          ...          ...          ...   
1254  2017-12-22  1061.109985  1064.199951  1059.439941  1060.119995   
1255  2017-12-26  1058.069946  1060.119995  1050.199951  1056.739990   
1256  2017-12-27  1057.390015  1058.369995  1048.050049  1049.369995   
1257  2017-12-28  1051.599976  1054.750000  1044.770020  1048.140015   
1258  2017-12-29  1046.719971  1049.699951  1044.900024  1046.400024   

        Adj Close   Volume  
0      359.288177  5115500  
1      359.496826  4666500  
2      366.600616  5562800  
3      365.001007  3332900  
4      364.280701  3373900  
...           ...      ...  
1254  1060.119995   755100  
1255  1056.739990   760600  
1256  1049.369995  1271900  
1257  1048.140015   837100  
1258  1046.400024   887500  

[1259 rows x 7 columns]

In [7]:
trainset = dataset_train.iloc[:,1:2].values

In [8]:
trainset

array([[ 357.385559],
       [ 360.122742],
       [ 362.313507],
       ...,
       [1057.390015],
       [1051.599976],
       [1046.719971]])

In [9]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0,1))
training_scaled = sc.fit_transform(trainset)

In [10]:
training_scaled

array([[0.01011148],
       [0.01388614],
       [0.01690727],
       ...,
       [0.97543954],
       [0.9674549 ],
       [0.96072522]])

In [11]:
x_train = []
y_train = []

In [12]:
for i in range(60,1259):
    x_train.append(training_scaled[i-60:i, 0])
    y_train.append(training_scaled[i,0])
x_train,y_train = np.array(x_train),np.array(y_train)

In [13]:
x_train.shape

(1199, 60)

In [14]:
x_train = np.reshape(x_train, (x_train.shape[0],x_train.shape[1],1))

In [15]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

Using TensorFlow backend.


In [16]:
regressor = Sequential()
regressor.add(LSTM(units = 50,return_sequences = True,input_shape = (x_train.shape[1],1)))

In [17]:
regressor.add(Dropout(0.2))


Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [18]:
regressor.add(LSTM(units = 50,return_sequences = True))
regressor.add(Dropout(0.2))

In [19]:
regressor.add(LSTM(units = 50,return_sequences = True))
regressor.add(Dropout(0.2))

In [20]:
regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

In [21]:
regressor.add(Dense(units = 1))

In [22]:
regressor.compile(optimizer = 'adam',loss = 'mean_squared_error')

In [23]:
regressor.fit(x_train,y_train,epochs = 100, batch_size = 32)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/100
1199/1199 [==============================] - 14s 12ms/step - loss: 0.0465
Epoch 2/100
1199/1199 [==============================] - 7s 6ms/step - loss: 0.0053
Epoch 3/100
1199/1199 [==============================] - 10s 8ms/step - loss: 0.0040
Epoch 4/100
1199/1199 [==============================] - 8s 7ms/step - loss: 0.0036
Epoch 5/100
1199/1199 [==============================] - 8s 6ms/step - loss: 0.0039
Epoch 6/100
1199/1199 [==============================] - 8s 7ms/step - loss: 0.0036
Epoch 7/100
1199/1199 [==============================] - 7s 6ms/step - loss: 0.0032
Epoch 8/100
1199/1199 [==============================] - 7s 6ms/step - loss: 0.0031
Epoch 9/100
1199/1199 [==============================] - 8s 7ms/step - loss: 0.0031
Epoch 10/100
1199/1199 [==============================] - 8s 7ms/step - loss: 0.0034
Epoch 11/100
1199/1199 [==============================] - 9s 

C:\Users\Siddarth\Anaconda3\lib\site-packages\keras\callbacks.py:122: UserWarning: Method on_batch_end() is slow compared to the batch update (1.439155). Check your callbacks.
  % delta_t_median)


  64/1199 [>.............................] - ETA: 1:28 - loss: 0.0012

C:\Users\Siddarth\Anaconda3\lib\site-packages\keras\callbacks.py:122: UserWarning: Method on_batch_end() is slow compared to the batch update (0.725562). Check your callbacks.
  % delta_t_median)


1199/1199 [==============================] - 19s 16ms/step - loss: 0.0014
Epoch 73/100
1199/1199 [==============================] - 15s 13ms/step - loss: 0.0013
Epoch 74/100
1199/1199 [==============================] - 14s 12ms/step - loss: 0.0014
Epoch 75/100
1199/1199 [==============================] - 14s 12ms/step - loss: 0.0013
Epoch 76/100
1199/1199 [==============================] - 14s 12ms/step - loss: 0.0016
Epoch 77/100
1199/1199 [==============================] - 15s 13ms/step - loss: 0.0014
Epoch 78/100
1199/1199 [==============================] - 14s 12ms/step - loss: 0.0012
Epoch 79/100
1199/1199 [==============================] - 16s 13ms/step - loss: 0.0015
Epoch 80/100
1199/1199 [==============================] - 16s 13ms/step - loss: 0.0012
Epoch 81/100
1199/1199 [==============================] - 18s 15ms/step - loss: 0.0012
Epoch 82/100
1199/1199 [==============================] - 18s 15ms/step - loss: 0.0012
Epoch 83/100
1199/1199 [==============================] 

In [24]:
dataset_test =pd.read_csv("testset.csv")

In [25]:
real_stock_price = dataset_test.iloc[:,1:2].values

In [27]:
dataset_total = pd.concat((dataset_train['Open'],dataset_test['Open']),axis = 0)
dataset_total

0       357.385559
1       360.122742
2       362.313507
3       365.348755
4       365.393463
          ...     
120    1143.599976
121    1128.000000
122    1121.339966
123    1102.089966
124    1120.000000
Name: Open, Length: 1384, dtype: float64

In [29]:
inputs = dataset_total[len(dataset_total) - len(dataset_test)-60:].values
inputs

array([ 955.48999 ,  966.700012,  980.      ,  980.      ,  973.719971,
        987.450012,  992.      ,  992.099976,  990.289978,  991.77002 ,
        986.      ,  989.440002,  989.52002 ,  970.      ,  968.369995,
        980.      , 1009.190002, 1014.      , 1015.219971, 1017.210022,
       1021.76001 , 1022.109985, 1028.98999 , 1027.27002 , 1030.52002 ,
       1033.98999 , 1026.459961, 1023.419983, 1022.590027, 1019.210022,
       1022.52002 , 1034.01001 , 1020.26001 , 1023.309998, 1035.      ,
       1035.869995, 1040.      , 1055.089966, 1042.680054, 1022.369995,
       1015.799988, 1012.659973,  995.940002, 1001.5     , 1020.429993,
       1037.48999 , 1035.5     , 1039.630005, 1046.119995, 1045.      ,
       1054.609985, 1066.079956, 1075.199951, 1071.780029, 1064.949951,
       1061.109985, 1058.069946, 1057.390015, 1051.599976, 1046.719971,
       1048.339966, 1064.310059, 1088.      , 1094.      , 1102.22998 ,
       1109.400024, 1097.099976, 1106.300049, 1102.410034, 1132.

In [30]:
inputs = inputs.reshape(-1,1)

In [31]:
inputs

array([[ 955.48999 ],
       [ 966.700012],
       [ 980.      ],
       [ 980.      ],
       [ 973.719971],
       [ 987.450012],
       [ 992.      ],
       [ 992.099976],
       [ 990.289978],
       [ 991.77002 ],
       [ 986.      ],
       [ 989.440002],
       [ 989.52002 ],
       [ 970.      ],
       [ 968.369995],
       [ 980.      ],
       [1009.190002],
       [1014.      ],
       [1015.219971],
       [1017.210022],
       [1021.76001 ],
       [1022.109985],
       [1028.98999 ],
       [1027.27002 ],
       [1030.52002 ],
       [1033.98999 ],
       [1026.459961],
       [1023.419983],
       [1022.590027],
       [1019.210022],
       [1022.52002 ],
       [1034.01001 ],
       [1020.26001 ],
       [1023.309998],
       [1035.      ],
       [1035.869995],
       [1040.      ],
       [1055.089966],
       [1042.680054],
       [1022.369995],
       [1015.799988],
       [1012.659973],
       [ 995.940002],
       [1001.5     ],
       [1020.429993],
       [10

In [32]:
inputs = sc.transform(inputs)
inputs.shape

(185, 1)